# Generated by Django 6.0 on 2025-12-05 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la línea de transporte.', max_length=255, verbose_name='Nombre de la Línea')),
                ('color', models.CharField(default='#000000', help_text='Color hexadecimal para representar la línea en mapas.', max_length=7, verbose_name='Color de la Línea')),
            ],
            options={
                'verbose_name': 'Línea',
                'verbose_name_plural': 'Líneas',
            },
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitud')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción del Punto')),
            ],
            options={
                'verbose_name': 'Punto Geográfico',
                'verbose_name_plural': 'Puntos Geográficos',
            },
        ),
        migrations.CreateModel(
            name='LineaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ruta', models.IntegerField(help_text='Identificador único para esta ruta dentro de la línea.', verbose_name='ID de Ruta')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción de la Ruta')),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Distancia (km)')),
                ('tiempo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tiempo Estimado (horas)')),
                ('id_linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='linea.lineas', verbose_name='Línea Asociada')),
            ],
            options={
                'verbose_name': 'Ruta de Línea',
                'verbose_name_plural': 'Rutas de Línea',
                'unique_together': {('id_linea', 'id_ruta')},
            },
        ),
        migrations.CreateModel(
            name='LineasPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(help_text='Posición secuencial del punto dentro de la ruta (1, 2, 3...).', verbose_name='Orden en la Ruta')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('distancia', models.DecimalField(decimal_places=2, help_text='Distancia desde este punto hasta el siguiente en la ruta.', max_digits=10, verbose_name='Distancia al siguiente punto')),
                ('tiempo', models.DecimalField(decimal_places=2, help_text='Tiempo estimado de recorrido desde el punto anterior hasta este.', max_digits=5, verbose_name='Tiempo de recorrido')),
                ('id_linea_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_en_ruta', to='linea.linearuta', verbose_name='Ruta')),
                ('id_punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_en_rutas', to='linea.puntos', verbose_name='Punto')),
            ],
            options={
                'verbose_name': 'Punto en Línea/Ruta',
                'verbose_name_plural': 'Puntos en Líneas/Rutas',
                'ordering': ['orden'],
                'unique_together': {('id_linea_ruta', 'orden')},
            },
        ),
    ]
