# Generated by Django 6.0 on 2025-12-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineas',
            name='color',
            field=models.CharField(default='#000000', help_text='Color hexadecimal para representar la línea en mapas.', max_length=7, verbose_name='Color de la Línea'),
        ),
    ]
